### ISSUE TITLE
jProf14 14-03-2017 Checklist

### ISSUE THREAD

**Issue by aliaksei-lithium** [JavaBy/Community#10]
## Подготовка:
- [x] Забронировать дату в Space(Руслан)
- [x] Написание анонса (Руслан)
- [x] Форма регистрации (Лёша)
- [x] Анонс запаблишить на [jprof.by](https://jprof.by/), [events.dev.by](https://events.dev.by/) и [@BelarusJUG](https://twitter.com/BelarusKUG)
[bjug.by](https://bjug.by), [Facebook](https://www.facebook.com/javaprofessionalsby/), [VK](https://vk.com/javaprofessionalsby)
- [x] Сделать рассылку анонса (Лёша)
- [x] Репост и рассылка от партнеров: Space, JavaDay
- [x] Прослушать Антонио (jprof)
- [x] Стикеры(принести Лёша)

Анонс можно расылать за неделю, и в день митапа. Должен содержать программу, ифно партнёров

## Пред Митапом
- [x] Договориться про Фотосъемка
- [x] Договориться про  Видеозапись
- [x] Уточнить что будет на Кофе-пауза

Фотосъемка - можно назначить ответсвенного, кто сделает десяток хороших кадров, либо заказать фотографа если есть средства на это.

Видеозапись - напомнить площадке что требуется видеозаписать, обсудить шаблон (то какая будет компоновка видео)

Вступительная речь - если требуется, заранее составить, дабы ничего не забыть.

Кофе-пауза - договориться о кофе-паузе

## Митап

- [x] Разложить стикеры
- [x] Выставить роллап
- [x] Объявление спикеров

## Пост Митап

- [x] Сделать опрос
- [x] Написать отчет на сайт, зарепостить везде
- [x] Ссылку на отчет и опрос отправить в рассылку на зарегистрированных участников
